/**
 * Skill Hints — reorder skills in a snapshot based on dispatch recommendations.
 *
 * Moves dispatch-recommended skills to the front of the skill arrays
 * without removing any skills. This influences the system prompt ordering
 * so the LLM is more likely to select the recommended skills.
 *
 * Also annotates the pre-built prompt string so that recommended skill names
 * are tagged with [推荐/Recommended] for LLM visibility.
 */

import type { SkillSnapshot } from "../agents/skills/types.js";

/**
 * Reorder skills in the snapshot so that hinted skills appear first.
 *
 * - Does NOT remove non-hinted skills — just prioritizes the hints.
 * - Does NOT modify the input snapshot — returns a new object.
 * - If no skill hints match any skills in the snapshot, returns the original.
 * - Annotates the prompt string to mark hinted skills as [推荐/Recommended].
 */
export function applySkillHints(snapshot: SkillSnapshot, skillHints: string[]): SkillSnapshot {
  if (skillHints.length === 0) return snapshot;

  const hintSet = new Set(skillHints);

  // Reorder the skills array
  const hinted = snapshot.skills.filter((s) => hintSet.has(s.name));
  const rest = snapshot.skills.filter((s) => !hintSet.has(s.name));

  // If no skills matched the hints, no change needed
  if (hinted.length === 0) return snapshot;

  // Similarly reorder resolvedSkills if present
  let resolvedSkills = snapshot.resolvedSkills;
  if (resolvedSkills) {
    const hintedResolved = resolvedSkills.filter((s) => hintSet.has(s.name));
    const restResolved = resolvedSkills.filter((s) => !hintSet.has(s.name));
    if (hintedResolved.length > 0) {
      resolvedSkills = [...hintedResolved, ...restResolved];
    }
  }

  // Annotate the pre-built prompt string: tag hinted skill names so the LLM
  // can see which skills are recommended by the dispatch engine.
  // The prompt is generated by formatSkillsForPrompt() from the pi-coding-agent
  // library and contains skill names in various contexts (XML tags, headings, etc.).
  let prompt = snapshot.prompt;
  if (prompt) {
    for (const hint of skillHints) {
      if (!hintSet.has(hint)) continue;
      // Match the skill name when it appears as a standalone token (not already tagged).
      // Common formats: "skill-name", "skill-name:", "<skill-name>"
      // CJK skill names don't have word boundaries, so use a lookaround-based
      // approach: match the name when NOT already tagged with [推荐].
      const escaped = hint.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const hasCJK = /[\u4e00-\u9fff\u3400-\u4dbf\uf900-\ufaff]/.test(hint);
      const re = hasCJK
        ? new RegExp(`(${escaped})(?! \\[推荐)`, "g")
        : new RegExp(`(\\b${escaped}\\b)(?! \\[推荐)`, "g");
      prompt = prompt.replace(re, `$1 [推荐/Recommended]`);
    }
  }

  return {
    ...snapshot,
    prompt,
    skills: [...hinted, ...rest],
    resolvedSkills,
  };
}
