// AUTO-GENERATED by scripts/generate-integrity-hashes.ts — DO NOT EDIT
// This constant is compiled into bytecode at build time.
// It stores the SHA-256 of integrity-hashes.json so that the file
// cannot be tampered with even if both disk files are replaced together.
// Run `pnpm integrity:gen` after each build to update this value.
// Generated: placeholder — run pnpm integrity:gen
export const INTEGRITY_ROOT_HASH = "";
